---
- include_tasks: pre_create_checks.yml

- include_tasks: remove_ca.yml
  when:
    - remove_ca

- name: Creating CA, Intermediate and Roles
  block:
    - include_tasks: create_ca.yml
    - include_tasks: create_intermediate.yml
    - include_tasks: create_role.yml
    - meta: end_play
  rescue:
    - include_tasks: remove_ca.yml
  when:
    - pki_check.status == 403
    - not remove_ca

- name: Creating Intermediate and Roles
  block:
    - include_tasks: create_intermediate.yml
    - include_tasks: create_role.yml
    - meta: end_play
  when:
    - pki_check.status == 200
    - pki_int_check.status == 403
    - not remove_ca

- name: Creating Roles
  block:
    - include_tasks: create_role.yml
    - meta: end_play
  when:
    - (pki_check.status == 200 and pki_int_check.status == 200) or new_role
    - not remove_ca
# tasks file for vault_certs
